#!/bin/bash
prefix=$1

mean=`grep -A 1 MEDIAN_INSERT_SIZE insert_size/insert_size.$prefix.txt | tail -n 1 | awk '{print $5-202}' | cut -f 1 -d \.`
stddev=`grep -A 1 MEDIAN_INSERT_SIZE insert_size/insert_size.$prefix.txt | tail -n 1 | awk '{print $6}' | cut -f 1 -d \.`

/usr/local/bin/ErrorCorrectReads.pl \
PHRED_ENCODING=33 \
PAIRED_READS_A_IN="cleandata/$prefix.unconnected.1.fq" \
PAIRED_READS_B_IN="cleandata/$prefix.unconnected.2.fq" \
PAIRED_SEP="$mean" \
PAIRED_STDEV="$stddev" \
PLOIDY=1 \
MAX_MEMORY_GB=200 \
THREADS=32 \
UNPAIRED_READS_IN="cleandata/$prefix.connected.fq" \
READS_OUT="ec_data/$prefix" \
1>log/error_correct.$prefix.stdout \
2>log/error_correct.$prefix.stderr


#Usage: /usr/local/bin/ErrorCorrectReads.pl arg1=value1 arg2=value2 ...
#
#Required arguments:
#
#PHRED_ENCODING
#  Fastq PHRED quality scores encoding (offset). Valid values are 33 or 64.
#READS_OUT
#  Error corrected output fastq file.
#
#Optional arguments:
#
#FILL_FRAGMENTS default: 0
#  Perform fragment filling step on error corrected paired reads.
#FORCE_PHRED default: 0
#  If True, ignore PHRED encoding warnings.
#KEEP_INTERMEDIATES default: 0
#  Keep intermediate files generated by ALLPATHS-LG pipeline.
#KEEP_KMER_SPECTRA default: 0
#  Save the kmer spectra generated during error correction
#MAX_MEMORY_GB default: 0
#  Restrict maximum memory usage - default is to use it all.
#PAIRED_READS_A_IN default: 
#  Fastq file containing the 1st (-->) paired reads to error correct.
#PAIRED_READS_B_IN default: 
#  Fastq file containing the 2nd (<--) paired reads to error correct.
#PAIRED_SEP default: -20
#  Paired read library mean separation. ( --A-->  sep  <--B-- )
#PAIRED_STDEV default: 30
#  Paired read library standard deviation.
#PLOIDY default: 2
#  Organism's ploidy. Used for evaluation purposes only. Valid values are 1 or 2.
#REMOVE_DODGY_READS default: 1
#  Run RemoveDodgyReads as part of the ALLPATHS-LG error correction pipeline.
#THREADS default: max
#  Number of threads to use in error correction.
#UNPAIRED_READS_IN default: 
#  Fastq file containing unpaired reads to error correct.
#
